### ISSUE TITLE
Alternate database: incorrect use of connection string?

### ISSUE THREAD

**Issue by jeromenerf** [xyproto/pstore#1]
permissionHSTORE provides a function to connect to a specific database instead of the user's default: 

```
func NewWithDSN(connectionString string, databaseName string) (*Permissions, error) {
```

This function then calls : 

```
func TestConnectionHostWithDSN(connectionString string) (err error) {
```

When parameters connectionstring `"user=myuser password=mypass sslmode=disable"` and dbname `somedb`, TestConnectionHostWithDSN will try to connect to a eventually non existing default db called `myuser`. If it exists, it will create `somedb` and create tables in `myuser`.

The correct connection string that seems to produce the expected result is `"user=myuser password=mypass dbname=somedb sslmode=disable"`.

See https://www.postgresql.org/docs/9.5/static/libpq-connect.html#LIBPQ-CONNSTRING

As a side note, it would be handy to provide a prefix for the permissions table, to be able to include them in an existing DB without conficts.

**Comment by xyproto** [comment]
Thanks for reporting, will look into the issue.

**Comment by siredwin** [comment]
@jeromenerf , @xyproto .
I also struggled with this for a full weekend.
The postgresql connection string here is a little bit different. 
The wrong connection string will default to a failed connection to the local username database and role.

Correct connection string:
` "postgres://user:pass@0.0.0.0:5432/postgres?sslmode=disable"`

Wrong connection string:
` "user:pass@0.0.0.0:5432/postgres?sslmode=disable"`

Do you have any comments about that?

**Comment by xyproto** [comment]
I have a branch going in simplehstore where I'm working to fix this. I encountered sone issues, so this is still a work in progress.

https://github.com/xyproto/simplehstore/commit/0b10a95c1f8c8d09975668e5c0ffa57a8ef8e9ce

Contributions or pull requests are warmly welcome too.

**Comment by siredwin** [comment]
I am fine that it works now! The connection string is actually ok too. 
For now,  I will use it that way and get back to it in the future when I have time. 

You could probably just document that too as I don't see anything wrong with it.
it is only the prefix `postgres://` that is needed.

**Comment by siredwin** [comment]
@xyproto ,
Please go ahead and close this issue, and document it.
I was going to contribute a fix but i realized that it needs none.
`TestConnectionHostWithDSN` and `NewHostWithDSN` both call `database/sql` directly. They also do not require your `rebuildConnectionString` helper.

So, the right connection string requires the prefix `"postgres://"` and is in the form `"postgres://user:pass@0.0.0.0:5432/postgres?sslmode=disable"`, which is the default connection string type.
Refer [LIBPQ-CONNSTRING](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING)

Also, I don't understand what that branch is trying to fix.

**Comment by xyproto** [comment]
Looking at my old code from when I first started learning Go, I also see several things that I would like to improve. Thanks for reviewing.

The point of the simplehstore branch was mainly to use an external package for dealing with the connection string format, instead of using custom code, to avoid duplicating work.

I really want to improve the code if there are anything that can be done to fix it or to improve the user experience. Would adding `postgres://` in front of the connection string if it's missing be a good solution?

**Comment by siredwin** [comment]
A good solution to most of your simplehstore complexity problems would be to accept the default connection string  with "postgres://" prefix in all calls.  It will also mean you won't be needing most of the helper functions.

**Comment by xyproto** [comment]
I believe this is fixed in `simplehstore` now. Several new tests were added. I will also look into removing the `rebuildConnectionString` function in the future.

Please confirm that it works as expected.

**Comment by siredwin** [comment]
I will test it later and let you know.

**Comment by siredwin** [comment]
`pstore` DSN connections still work with the default connection string with `postgres://` prefix.

**Comment by xyproto** [comment]
Thanks for the feedback and thanks for testing.
