### ISSUE TITLE
Find ID By FieldValue

### ISSUE THREAD

**Issue by siredwin** [xyproto/pstore#2]
Hello,
Will this `state.users.FindIDByFieldValue("email", email)` be available for pstore? I am waiting to test it.

**Comment by xyproto** [comment]
`state.users.AllWhere("email", email)` is already available.

**Comment by siredwin** [comment]
Thanks. I can see a lot of difference

**Comment by xyproto** [comment]
Great! 😊

**Comment by siredwin** [comment]
I have one more request to ask.
I am trying to stay away from loops in search of user ids.
Given the following  `	err = Userstate.Users().Set(userid, "secret", secret) 
Would it be possible to get a generic function that does something similar to already fixed problem without loops?
I only happen to know key names and values

```
func getValueFromKey(keyname, keyvalue string) (string, error){
    name, err := state.users.AllWhere(keyname, keyvalue)
    return
}

//usage
userid, err := getValueFromKey("email", email)
userid, err := getValuefromKey("secret", secret)
```

`

**Comment by siredwin** [comment]
```

func (state *UserState) GetValue(key, value string) (usernames []string,err error) {
	if value == "" {
		return usernames, ErrNotFound
	}
	usernames, err = state.users.AllWhere(key, value)
	return
}
````
